import React, { Component, FunctionComponent } from "react";

export const Text: FunctionComponent = () => (
  <React.Fragment>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam mollis mi tristique nisl maximus tristique. Etiam a diam metus. Suspendisse vitae augue lectus. Nunc mollis turpis sit amet orci pellentesque, at dictum lectus finibus. Integer lacus nisl, bibendum vel fermentum ut, pulvinar et metus. Ut euismod volutpat urna, vitae venenatis est cursus et. Integer nec placerat lectus. Praesent sit amet volutpat risus. Aenean vel imperdiet nisi.

      Curabitur maximus ultricies diam eu maximus. In sit amet massa eu dui tempor pellentesque. In magna dolor, consectetur non turpis id, tincidunt ultricies velit. Proin vel arcu malesuada, luctus sem nec, elementum orci. Pellentesque facilisis nisi sed nulla sodales vehicula. Vivamus condimentum luctus lectus ac faucibus. Proin efficitur tellus eget nisl iaculis, in tristique elit sollicitudin. Nulla in placerat ex. Fusce id tortor vestibulum, commodo leo id, ultricies orci. Suspendisse sollicitudin nisi dui, nec finibus massa placerat ac. Aliquam dictum vulputate ipsum ut sollicitudin. Suspendisse ultrices felis at lacus tempus, quis sollicitudin lacus feugiat. Nullam sapien ante, venenatis eu sollicitudin eget, ornare ornare erat.
    </p>
    <p>
    Maecenas commodo lectus non leo condimentum imperdiet. Nulla sit amet eros et lorem posuere scelerisque. Etiam consequat mauris ac dolor aliquam laoreet. Ut in ipsum et quam volutpat luctus. Integer condimentum purus quis neque vehicula viverra. Etiam tempor dui eu diam iaculis bibendum. Duis placerat ipsum in neque varius ornare. Aliquam at turpis tortor. Duis interdum lobortis nulla ac porttitor. Etiam in gravida mauris, eu mollis massa. Aenean pellentesque hendrerit massa, eget ornare nunc tincidunt sed. Mauris sodales tincidunt magna quis feugiat.

    Maecenas non tellus non erat lacinia pulvinar sit amet et urna. Nulla vehicula, risus at facilisis sodales, nisi enim convallis ligula, nec tristique erat dolor quis velit. Vestibulum sodales vulputate quam, aliquam tristique lacus pretium pretium. Etiam et elit nec libero porta molestie. Maecenas pellentesque arcu faucibus vestibulum tempus. Cras fringilla, urna ornare imperdiet accumsan, tellus massa dictum enim, ut tincidunt sapien risus ac sapien. Sed egestas dapibus quam, eget hendrerit nisl commodo vitae. Sed purus enim, congue eu purus ac, pellentesque lacinia est. Vivamus orci libero, tincidunt nec odio sed, gravida ultrices est. Nam semper quam elit, a tempus dolor viverra venenatis. Morbi non velit dignissim, egestas mi sed, malesuada quam. Nulla facilisi. Cras facilisis lacus nec quam faucibus hendrerit. Fusce ac vehicula ex.

    Ut sodales ultrices mauris, eget tempor leo scelerisque ut. Nullam commodo, ex sit amet efficitur tincidunt, tellus neque maximus lorem, sit amet ornare velit eros vel nunc. Fusce non lobortis nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce id ligula eget leo varius imperdiet luctus quis ipsum. Proin et gravida enim, ut rhoncus nibh. Sed et neque euismod, gravida nunc vel, dapibus arcu. Curabitur mattis odio ac lorem porta ultrices. Fusce ipsum enim, porttitor ac quam et, suscipit interdum neque. Sed a convallis ligula, in sagittis eros. Proin iaculis enim enim, id commodo neque auctor sed.</p>
  </React.Fragment>
)